### PR TITLE
Fixes addPerson user feedback

### LINKED ISSUE #118: Improve logging statements for AddPerson Command
Image

Change it to just show the details of the person added rather than (seedu...) which exposes the internal parts of our code

Format also applies to other weddingOverview

Image

### PR DESCRIPTION
**Pull request by jonzyyyy**
Displays the full name of person

image

image

Fixes #118

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -225,9 +224,7 @@ public int hashCode() {
 
     @Override
     public String toString() {
-        return new ToStringBuilder(this).add("name", name).add("phone", phone).add("email", email)
-                .add("address", address).add("tags", tags).add("dietaryRestriction", dietaryRestriction)
-                .add("rsvp", rsvp).add("table", getTableIdString()).toString();
+        return this.getName().toString();
```
Comment (josejhkim) [inline src/main/java/seedu/address/model/person/Person.java:227]: Perhaps we can change this later to display other informations that may be useful for the wedding managers to see.

**Review by josejhkim — APPROVED** [review]
LGTM!
